### ISSUE TITLE
Pod::Checker issues bogus warnings

### ISSUE THREAD

**Issue by tobyink** [cpants/Module-CPANTS-SiteKwalitee#7]
```
=begin ignoreme

=item foo

=end
```

Pod::Checker will complain about `=item` not being between `=over` and `=back`, but any text between `=begin` and `=end` shouldn't be assumed to be pod syntax. Please revert back to Pod::Simple::Checker.

**Comment by karenetheridge** [comment]
According to the pod spec (`perldoc perlpod`), content labelled with a colon (e.g. `for foo` or between `=begin :foo` and `=end :foo`) will be pod, and labels without a colon could be plain text or anything at all. Pod::Simple's parser should understand this.

**Comment by charsbar** [comment]
Thanks for your heads-up. I reverted back to Pod::Simple::Checker and started regenerating databases, which I hope will end in a day.
